version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: "poetry run jupyter lab --no-browser --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.disable_check_xsrf=True"
